name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build 8.2 image
      run: docker build . --file Dockerfile --tag 'php:8.2.0-alpine3.17-swoole-5.0.1' --tag 'php:8.2.0-swoole' --tag 'php:alpine3.17-swoole' --tag 'php:alpine-swoole' --tag 'swoole'
    - name: Build 8.1 image
      run: docker build . --file Dockerfile-8.1 --tag php:8.1.13-alpine3.17-swoole-5.0.1
    - name: Publish image
      run: for i in $(docker images | grep php | awk 'BEGIN{OFS=":"}{print $1,$2}'); do docker push $i; done
